---
title: "Investigating content and audience reactions to youtube Super Bowl commercials"
subtitle: "(2000 to 2020)"
author: "R_mageddon <br> Yihan Shi, Holly, Cui, Raffay Rana"
institute: "Duke University"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r load-packages, include = FALSE}
# Add any additional packages you need to this chunk
# Remove any packages from this list that you're not using
library(tidyverse)
library(tidymodels)
library(palmerpenguins)
library(knitr)
library(xaringanthemer)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(wordcloud2)
library(ggwordcloud)
library(tidytext)
library(syuzhet)
library(stringr)
library(textdata)
library(hrbrthemes)
library(scales)
```

```{r setup, include = FALSE}
# For better figure resolution
knitr::opts_chunk$set(
  fig.retina = 3, 
  dpi = 300, 
  fig.width = 6, 
  fig.asp = 0.618, 
  out.width = "70%"
  )
```

```{r load-data, include = FALSE}
youtube <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-02/youtube.csv', 
                           show_col_types = FALSE)
```

```{r style-slides, echo = FALSE}
style_xaringan(
  title_slide_background_image = "img/watercolour_sys02_img34_teacup-ocean.jpg"
)
```



``` {r election-col, echo = FALSE, warning = FALSE}
# Creating variable with election, using pivot_longer to get attributes in the
# same column, and creating a percentage variable
election_year <- c(2000, 2004, 2008, 2012, 2016, 2020)
# Adding an election year variable
youtube <- youtube %>%
  mutate(election_years = ifelse(year %in% election_year, 1, 0))
election_yr <- youtube %>%
  pivot_longer(cols = c(use_sex, funny, celebrity, patriotic, danger, animals)) %>%
  filter(election_years == 1) %>%
  filter(value == TRUE) %>%
  group_by(name) %>%
  summarise(n = n()) %>%
  mutate(perc = paste(round((n / sum(n)) * 100), "%", sep = ""))
```


### Content Comparision

.pull-left[
``` {r election-col-plot, out.width = "130%", fig.width = 15, fig.height = 20, echo = FALSE, warning = FALSE}
# Creating the plot
election_yr %>%
  ggplot(aes(y = name, x = n, fill = name)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = perc, color = name), nudge_x = 2, show.legend = FALSE,
            size = 8) +
  labs(
    x = "Count",
    y = "Ad Attribute",
    title = "Count and Proportion of Ad by Attribute",
    subtitle = "In Election Years"
  ) +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal()+
  theme(text = element_text(size = 25)) +
  scale_y_discrete(labels = rev(c("Use Sex",
                              "Patriotic",
                              "Funny",
                              "Danger",
                              "Celebrity",
                              "Animals")))
```
]

```{r non-election-col, echo = FALSE, warning = FALSE}
# Creating variable with no election, using pivot_longer to get attributes in the
# same column, and creating a percentage variable
no_election_yr <- youtube %>%
  pivot_longer(cols = c(use_sex, funny, celebrity, patriotic, danger, animals)) %>%
  filter(election_years == 0) %>%
  filter(value == TRUE) %>%
  group_by(name) %>%
  summarise(n = n()) %>%
  mutate(perc = paste(round((n / sum(n)) * 100), "%", sep = ""))
```

.pull-right[
```{r non-election-col-plot, out.width = "130%", fig.width = 15, fig.height = 20, echo = FALSE, warning = FALSE}
# No Election year col vizualization
no_election_yr %>%
  ggplot(aes(y = name, x = n, fill = name)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = perc, color = name), nudge_x = 4, show.legend = FALSE,
            size = 8) +
  labs(
    x = "Count",
    y = "Ad Attribute",
    title = "Count and Proportion of Ad by Attribute",
    subtitle = "In Non-Election Years"
  ) +
  scale_fill_brewer(palette = "Dark2") +
  scale_color_brewer(palette = "Dark2") +
  theme_minimal() +
  theme(text = element_text(size = 25)) +
  scale_y_discrete(labels = rev(c("Use Sex",
                              "Patriotic",
                              "Funny",
                              "Danger",
                              "Celebrity",
                              "Animals")))

```
]


---


## How do election year ads differ from non-election year ads in terms of content and description?

.center[
``` {r data-prep-election-wordcloud, echo = FALSE, warning = FALSE}
# # Election years in the dataset
election_year <- c(2000, 2004, 2008, 2012, 2016, 2020)
# Adding an election year variable
youtube <- youtube %>%
  mutate(election_years = ifelse(year %in% election_year, 1, 0))

test <- youtube %>%
  filter(election_years == 1) %>%
  select(title)

docs <- VCorpus(VectorSource(test))
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, c(
  "super", "bowl", "commercial", "superbowl",
  "bud", "light", "budweiser", "pepsi",
  "hyundai", "doritos", "coke", "cocacola",
  "cola", "coca", "kia", "toyota"
))
dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing = TRUE)
election_df <- data.frame(word = names(words), freq = words)


election_df <- election_df %>%
  mutate(angle = sample(-45:45, nrow(election_df), replace = TRUE)) %>%
   # Package to get sentiment scores for each word in the dataset
  mutate(sentiment = get_sentiment(word,"syuzhet"))
```

``` {r election-wordcloud-viz, warning = FALSE, out.width = "90%", fig.width = 10, fig.height = 11, echo = FALSE}
elec_word_C <-election_df %>%
  ggplot(aes(
    label = word,
    color = sentiment,
    size = freq,
    angle = angle
  )) +
  geom_text_wordcloud() +
  scale_radius(range = c(2, 15)) +
  theme_minimal() +
  scale_color_gradient(low = "#FFD662FF", high = "#00539CFF") +
  labs(
    title = "Election Year Ad Title Word Cloud",
    subtitle = "Colored by Sentiment
      Bluer for postive sentiments
      Yellower for negative sentiment"
  )
```

```{r non-election-wordcloud-data-prep, echo = FALSE, warning = FALSE}
# Isolating the title variable
no_election_title <- youtube %>%
  filter(election_years == 0) %>%
  select(title)

#Data Wrangling steps
docs <- VCorpus(VectorSource(no_election_title))
docs <- docs %>%
  # Removing numbers
  tm_map(removeNumbers) %>%
  # Removing punctuation
  tm_map(removePunctuation) %>%
  # Removing whitespace
  tm_map(stripWhitespace)

# transforming words to lowercase
docs <- tm_map(docs, content_transformer(tolower))
# removing words that contain brand names
docs <- tm_map(docs, removeWords, c(
  "super", "bowl", "commercial", "superbowl",
  "bud", "light", "budweiser", "pepsi",
  "hyundai", "doritos", "coke", "cocacola",
  "cola", "coca", "the", "kia","toyota"
))

# Creating df that can be used by ggwordcloud
dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing = TRUE)
non_election_df <- data.frame(word = names(words), freq = words)

# Adding the sentiment score variable
non_election_df <- non_election_df %>%
  mutate(angle = sample(-45:45, nrow(non_election_df), replace = TRUE)) %>%
  filter(freq >= 2) %>%
  mutate(sentiment = get_sentiment(word,"syuzhet"))
```


``` {r non-election-wordcloud-viz, out.width = "90%", fig.width = 10, fig.height = 11, echo = FALSE, warning = FALSE}
no_elec_wordC <- non_election_df %>%
  ggplot(aes(
    label = word,
    color = sentiment,
    size = freq,
    angle = angle
  )) +
  geom_text_wordcloud() +
  scale_radius(range = c(3.5, 15)) +
  theme_minimal() +
  scale_color_gradient(low = "#FFD662FF", high = "#00539CFF")+
  labs(
    title = "Non-election Year Ad Title Word Cloud")

library(patchwork)
elec_word_C / no_elec_wordC

```
]

---