---
title: "Raffay Plot 2"
output: html_document
---



```{r}
library(tidyverse)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(wordcloud2)

knitr::opts_chunk$set(echo = TRUE)
youtube <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-02/youtube.csv', show_col_types = FALSE)

election_year <- c(2000,2004,2008,2012,2016,2020)
youtube <- youtube %>% 
  mutate(election_years = ifelse(year %in% election_year,1,0)) 

test <- youtube %>% 
          filter(election_years == 1) %>% 
          select(title)

docs <- Corpus(VectorSource(test))
docs
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
docs <- tm_map(docs, removeWords, c("super","bowl","commercial","superbowl",
                                    "bud","light","budweiser","pepsi",
                                    "hyundai","doritos","coke","cocacola",
                                    "cola","coca","kia","toyota"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)

set.seed(1234) # for reproducibility 
wordcloud(words = df$word, 
          freq = df$freq,
          min.freq = 1,
          max.words=100, 
          random.order=FALSE, 
          rot.per=0.35,
          colors=brewer.pal(8, "Dark2"))

# Next Steps
# Filter for Brand Names 
# Make Frequency Charts for the attributes 


# Way to create summary table with column names 
election_yr <- youtube %>% 
  pivot_longer(cols = c(use_sex,funny,celebrity,patriotic,danger,animals)) %>% 
  filter(election_years == 1) %>% 
  filter(value == TRUE) %>% 
  group_by(name) %>% 
  summarise(n = n()) %>% 
  mutate(perc = paste(round((n / sum(n))*100),"%",sep = ""))

election_yr %>% 
  ggplot(aes(y = name, x = n, fill = name)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = perc, color = name), nudge_x = 2, show.legend = FALSE) +
  labs(
    x = "Count",
    y = "Ad Attribute",
    title = "Count and Proportion of Ad by Attribute",
    subtitle = "In Election Years"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("Grey","Grey","Grey","Grey","Red","Grey")) +
  scale_color_manual(values = c("Grey","Grey","Grey","Grey","Red","Grey"))
 


```

```{r}


test2 <- youtube %>% 
          filter(election_years == 0) %>% 
          select(title)

docs <- Corpus(VectorSource(test2))
docs
docs <- docs %>%
  tm_map(removeNumbers) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, c("super","bowl","commercial","superbowl",
                                    "bud","light","budweiser","pepsi",
                                    "hyundai","doritos","coke","cocacola",
                                    "cola","coca","the","kia"))
dtm <- TermDocumentMatrix(docs) 
matrix <- as.matrix(dtm) 
words <- sort(rowSums(matrix),decreasing=TRUE) 
df <- data.frame(word = names(words),freq=words)

set.seed(1234) # for reproducibility 
wordcloud(words = df$word, 
          freq = df$freq,
          min.freq = 1,
          max.words=100, 
          random.order=FALSE, 
          rot.per=0.35,
          colors=brewer.pal(8, "Dark2"))

wordcloud2(data=df, size=1.6, color='random-dark')

# Next Steps
# Filter for Brand Names 
# Make Frequency Charts for the attributes 


```



```{r}

# Way to create summary table with column names 
# Way to create summary table with column names 
no_election_yr <- youtube %>% 
  pivot_longer(cols = c(use_sex,funny,celebrity,patriotic,danger,animals)) %>% 
  filter(election_years == 0) %>% 
  filter(value == TRUE) %>% 
  group_by(name) %>% 
  summarise(n = n()) %>% 
  mutate(perc = paste(round((n / sum(n))*100),"%",sep = "")) 

no_election_yr %>% 
  ggplot(aes(y = name, x = n, fill = name)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = perc, color = name), nudge_x = 3.5, show.legend = FALSE) +
  labs(
    x = "Count",
    y = "Ad Attribute",
    title = "Count and Proportion of Ad by Attribute",
    subtitle = "In Election Years"
  ) +
  theme_minimal() +
  scale_fill_manual(values = c("Grey","Grey","Grey","Grey","Red","Grey")) +
  scale_color_manual(values = c("Grey","Grey","Grey","Grey","Red","Grey"))
 

```

